paths:
  /users/auth:
    post:
      tags:
        - Users
      summary: Autenticar usuário
      description: Realiza login de usuário no sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "joao.silva@email.com"
                  description: Email do usuário
                password:
                  type: string
                  minLength: 6
                  example: "minhasenha123"
                  description: Senha do usuário
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: "b2c3d4e5-f6g7-8901-bcde-2345678901bc"
                        description: ID único do usuário
                      name:
                        type: string
                        example: "João Silva"
                        description: Nome do usuário
                      email:
                        type: string
                        format: email
                        example: "joao.silva@email.com"
                        description: Email do usuário
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-09-11T10:30:00Z"
                        description: Data de criação do usuário
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-09-11T10:30:00Z"
                        description: Data da última atualização do usuário
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    description: Token JWT para autenticação
        '400':
          description: Credenciais inválidas ou usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid password"
                    description: Mensagem de erro
        '422':
          description: Dados de entrada inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Validation failed"
                    description: Mensagem de erro de validação
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: "email"
                        message:
                          type: string
                          example: "Email deve ser um email válido"
