paths:
  /users:
    post:
      tags:
        - Users
      summary: Criar um novo usuário
      description: Cria um novo usuário no sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: "João Silva"
                  description: Nome do usuário
                email:
                  type: string
                  format: email
                  example: "joao.silva@email.com"
                  description: Email do usuário
                password:
                  type: string
                  minLength: 6
                  example: "minhasenha123"
                  description: Senha do usuário (mínimo 6 caracteres)
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: "b2c3d4e5-f6g7-8901-bcde-2345678901bc"
                    description: ID único do usuário
                  name:
                    type: string
                    example: "João Silva"
                    description: Nome do usuário
                  email:
                    type: string
                    format: email
                    example: "joao.silva@email.com"
                    description: Email do usuário
                  created_at:
                    type: string
                    format: date-time
                    example: "2025-09-11T10:30:00Z"
                    description: Data de criação do usuário
                  updated_at:
                    type: string
                    format: date-time
                    example: "2025-09-11T10:30:00Z"
                    description: Data da última atualização do usuário
        '400':
          description: Dados inválidos ou email já existe
