paths:
  /users:
    delete:
      tags:
        - Users
      security:
        - BearerAuth: []
      summary: Deletar conta do usuário logado
      description: Remove a conta do usuário autenticado através do token JWT
      responses:
        '200':
          description: Usuário deletado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User deleted successfully"
        '404':
          description: Usuário não encontrado
        '400':
          description: Erro ao deletar usuário
