paths:
  /users/{id}:
    delete:
      tags:
        - Users
      summary: Deletar um usuário
      description: Remove um usuário do sistema
      parameters:
        - name: id
          in: path
          required: true
          description: ID do usuário a ser deletado
          schema:
            type: string
            format: uuid
          example: "b2c3d4e5-f6g7-8901-bcde-2345678901bc"
      responses:
        '200':
          description: Usuário deletado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User deleted successfully"
        '404':
          description: Usuário não encontrado
        '400':
          description: Erro ao deletar usuário
