paths:
  /users:
    put:
      tags:
        - Users
      security:
        - BearerAuth: []
      summary: Atualizar dados do usuário logado
      description: Atualiza nome, email ou senha do usuário autenticado através do token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Novo nome do usuário
                email:
                  type: string
                  format: email
                  description: Novo email do usuário
                password:
                  type: string
                  minLength: 6
                  description: Nova senha do usuário (mínimo 6 caracteres)
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: "b2c3d4e5-f6g7-8901-bcde-2345678901bc"
                    description: ID único do usuário
                  name:
                    type: string
                    example: "João Silva Santos"
                    description: Nome do usuário
                  email:
                    type: string
                    format: email
                    example: "joao.santos@email.com"
                    description: Email do usuário
                  created_at:
                    type: string
                    format: date-time
                    example: "2025-09-11T10:30:00Z"
                    description: Data de criação do usuário
                  updated_at:
                    type: string
                    format: date-time
                    example: "2025-09-11T12:45:00Z"
                    description: Data da última atualização do usuário
        '400':
          description: Dados inválidos ou email já existe
        '404':
          description: Usuário não encontrado
