services:
  mysql:
    image: mysql:8.0
    container_name: node-js-test-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: node_js_test
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node-js-test-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: node-js-test-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

  api:
    build: .
    container_name: node-js-test-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
      API_PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASS: app_password
      DB_NAME: node_js_test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      JWT_PASS: liguelead
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge

