/plans:
  post:
    tags:
      - Plans
    summary: Cria um novo plano (apenas administradores).
    security:
      - BearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                example: "Plano Premium"
              resources:
                type: array
                items:
                  type: string
                description: Recursos inclusos no plano
                example: ["Acesso completo à plataforma", "suporte premium", "relatórios avançados"]
              price:
                type: number
                example: 299.99
              duration:
                type: integer
                example: 12
              budgets:
                type: integer
                example: 50
              favorites:
                type: integer
                example: 100
                description: Número de favoritos permitidos (opcional)
              type:
                type: string
                enum: ["user", "provider"]
                example: "user"
                description: Tipo de usuário do plano - user ou provider (opcional)
              monitored:
                type: integer
                example: 25
                description: Número de itens monitorados permitidos (opcional)
              credits:
                type: integer
                example: 100
                description: Número de créditos inclusos no plano (opcional)
    responses:
      201:
        description: Plano criado com sucesso
        content:
          application/json:
            example:
              plan:
                id: "0720a8f5-df8e-4356-9216-e84a4f67aa1f"
                name: "Plano Premium"
                resources: ["Acesso completo à plataforma", "suporte premium"]
                price: 299.99
                duration: 12
                budgets: 50
                favorites: 100
                type: "user"
                monitored: 25
                credits: 100
      "409":
        description: Conflict - Plano já existe
      "400":
        description: Bad request
      "401":
        description: Unauthorized - Token não fornecido ou inválido
      "403":
        description: Forbidden - Acesso restrito a administradores
