paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Listar todas as tarefas
      description: Retorna uma lista com todas as tarefas do sistema, independente do projeto
      responses:
        '200':
          description: Lista de tarefas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    project_id:
                      type: string
                      format: uuid
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                      enum: [todo, in_progress, done]
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
        '400':
          description: Erro ao buscar tarefas
